# - name: install and run nginx
#   hosts: 172.31.23.113
#   become: yes #equal to -b in adhoc command, getting root acees
#   tasks:
#   - name: install nginx
#     ansible.builtin.dnf:
#       name: nginx
#       state: latest
#   - name: start nginx
#     ansible.builtin.service:
#       name: nginx
#       state: started
#       enabled: yes


- name: install and run mysql
  hosts: web #172.31.23.112
  become: yes #equal to -b in adhoc command ,getting root accesss
  tasks:
  - name: install mysql
    ansible.builtin.dnf:
      name: mysql
      state: latest
  - name: start mysql
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes    

