- name: PLAY-1
  hosts: localhost
  tasks:
  - name: PLAY-1 and TASK-1
    ansible.builtin.debug: #print mesg
      msg: "Hello I am from PLAY-1 and Tasl-2"

- name: PLAY-2
  hosts: localhost
  tasks:
  - name: PLAY-2 and TASK-2
    ansible.builtin.debug: #print mesg like echo
      msg: "Hello I am from PLAY-2 and Task-2"  

- name: PLAY-3
  hosts: localhost
  tasks:
  - name: PLAY-3 and TASK-3
    ansible.builtin.debug: #print mesg like echo
      msg: "Hello I am from PLAY-3 and Task-3"  


- name: PLAY-4
  hosts: localhost
  tasks: 
  - name: PLAY_4 and TASK-4
    ansible.builtin.debug:
      msg: " Hello I am from PLAY-4 and Task-4"        