- name: variable from files
  hosts: localhost
  vars_files: #calling var.yaml
  - vars.yaml
  tasks:
  - name: print override information
    #vars: #Task level variables
    course: "DevOps"
    ansible.builtin.debug:
      msg: "Hi, we are learing {{course}} from Trainer {{Trainer}}, Duration is {{Duration}}"  