- name: variable from files
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: please enter your username
    private: false
  - name: PASSWORD
    prompt: Please enter your password
    private: false
  tasks:
  - name: print override information
    ansible.builtin.debug:
      msg: "Hi, Username {{USERNAME}} and Password {{PASSWORD}}"  