- name: variable from files
  hosts: localhost
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi , we are learing {{fee}} from Trainer {{school}}, Duration  is {{class}}."