- name: variables from files
  hosts: localhost
  tasks:
  - name: print information
    vars:
      timings: "4:23AM IST"
    ansible.builtin.debug:
      msg: "Timings are:{{timings}}, Hi , we are learing {{Course}} from Trainer {{Trainer}}, Duration  is {{Duration}}."
  